baseURL: https://aaryamanduggal.netlify.app/
languageCode: en-us
title: Portfolio Website for Aaryaman Duggal 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Explore
    subtitle: |-
      This is the website Project for Data Analytics for Finance. RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Aaryaman Duggal
  blog: {}
  contact: 
    address:  
      - city: London
        country: United Kingdom 
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: aduggal.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (91) 9953726945
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer: 
    copyright: Company Name 
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1: 
    - name: Explore
      url: blogs
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/aliquam
    menu: Menu
    subtitle: Portfolio Website
    title: Aaryaman Duggal 
  tiles:
    enable: yes
    showcase:
      - image: pic.jpg
        subtitle: Know More About Me
        title: About Me
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: ## continents | countries 
        title: Travel
        url: blogs/tempus
      - image: pic09.jpg
        subtitle: Cars and me - A love story
        title: Motorhead
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Data Analytics and Quantitative Projects
        title: Projects
        url: blogs/ipsum
    
